#!/bin/bash

DEFAULT_BAT="BAT0"

if [ $# -eq 2 ]; then
   SHORT=1
   BATN=$2
elif [ $# -eq 1 ] && [ $1 = "-s" ]; then
   SHORT=1
   BATN=$DEFAULT_BAT
elif [ $# -eq 1 ]; then
   SHORT=0
   BATN=$1
else
   SHORT=0
   BATN=$DEFAULT_BAT
fi

SMAPI=/sys/devices/platform/smapi/$BATN
ACPI=/proc/acpi/battery/$BATN

if [ $SHORT -eq 1 ]; then
   [ -d $SMAPI ] || { echo "${BATN:0-1:1}:N/A"; exit; }
else
   [ -d $SMAPI ] || { echo "SMAPI directory not present"; exit; }
fi

STATE=`cat $SMAPI/state`
PERCENT=`cat $SMAPI/remaining_percent`

case "$STATE" in
   "charging")
      TIME=`cat $SMAPI/remaining_charging_time`
      if [ "$TIME" = "not_charging" ]; then TIME="N/A"; fi
      if [ $SHORT -eq 1 ]; then
         echo "C:${PERCENT}%|${TIME}m"
      else 
         echo "Charging: ${PERCENT}% (${TIME}m remaining)"
      fi
      ;;
   "discharging")
      TIME=`cat $SMAPI/remaining_running_time`
      CAP=`cat $SMAPI/remaining_capacity`
      FULL=`cat $SMAPI/design_capacity`
      if [ -d $ACPI ]; then
         RATE=`grep "present rate" $ACPI/state | egrep -o "[0-9]+"`
      else
         RATE="N/A"
      fi
      if [ "$TIME" = "not_discharging" ]; then TIME="N/A"; fi
      if [ $SHORT -eq 1 ]; then
         echo "D:${PERCENT}%|${TIME}m" 
      else
         echo "Discharging: ${PERCENT}% (${TIME}m remaining, ${CAP}mWh/${FULL}mWh @ ${RATE}mW)"
      fi
      ;;
   "idle")
      if [ $SHORT -eq 1 ]; then
         echo "I:${PERCENT}%"
      else
         echo "Idle: ${PERCENT}%"
      fi
      ;;
   *)
      if [ $SHORT -eq 1 ]; then
         echo "${BATN:0-1:1}:N/A"
      else
         echo "Unknown state: $STATE"
      fi
      ;;
esac
