#!/bin/bash

TC=$(which tc)
IP=$(which ip)
IPT=$(which iptables)

if [ $# -eq 1 ]; then
	IF="eth$1"
	INDEV="imq$1"
	IMQ=$1
elif [ $# -eq 2 -a "${2:0:3}" = "ifb" ]; then
	IF=$1
	INDEV=$2
elif [ $# -eq 2 ]; then
	IF=$1
	INDEV="imq$2"
	IMQ=$2
else
	echo -e "usage: $0 <ethnum>\n       $0 <iface> <imqnum>\n       $0 <iface> <ifbdev>"
	exit
fi

echo "esfq: $IF/$INDEV"

$TC qdisc del dev $IF root 2> /dev/null || true
$TC qdisc add dev $IF root esfq perturb 20 hash src

$TC qdisc del dev $INDEV root 2> /dev/null || true
$TC qdisc add dev $INDEV root esfq perturb 20 hash dst

$IP link set $INDEV up

if [ ${INDEV:0:3} = "ifb" ]; then
	$TC qdisc add dev $IF ingress
	$TC filter add dev $IF parent ffff: protocol ip prio 10 u32 \
	    match u32 0 0 flowid 1:1 \
	    action mirred egress redirect dev $INDEV
else
	$IPT -t mangle -A PREROUTING -i $IF -j IMQ --todev $IMQ
fi
